export enum paths {
  home = "/",
  login = "/login",
  profile = "/profile",
  statistics = "/statistics",
  notifications = "/notifications",
  notFound = "/*",
  profileSettings = "/settings",
  profilePassword = "/password",
  profileInfo = "/info",
  locationAdd = "/add_location",
  directionAdd = "/add_direction",
  locationEdit = "/edit_location",
  directionEdit = "/adit_direciton",
}
